### ISSUE TITLE
Fnalibs/Launcher for other games?

### ISSUE THREAD

**Issue by moocow1452** [daniel-j/fnalibs-celeste#1]
How involved would it be to configure more addin libraries or an entire launcher solution for other FNA games as a lot of them are available through Itch or Humble or GOG, and maybe even Steam versions could be playable with Box86 weirdness.

**Comment by kode54** [comment]
This may also be a springboard for "porting" macOS versions of games from running under Rosetta 2 to running natively. Terraria is a candidate, in my opinion, because it's heavily CPU dependent, especially late game, and Rosetta 2 means it's running a double-JIT, hence why it tends to perform like crap unless you turn off the interpolated lighting.

Incidentally, the dependencies already bundled with the game are weird. Several of them are already dual x86_64/aarch64. A few of them are astonishingly i386/x86_64, which is just plain silly.
